name: Doc Deploy

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  doc-deploy:
    name: Doc Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest

      - name: "Deploy documentation"
        uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
